#!/usr/bin/python
import csv

PATH_FOOD = 'foods/food.csv'

with open(PATH_FOOD, 'r') as f:
    csvreader = csv.reader(f)
    header = csvreader.__next__()
    for row in csvreader:
        print(row)
        #print(len(row))
